### ISSUE TITLE
hi, 请教博主一个问题

### ISSUE THREAD

**Issue by FatDong1** [linguowei/myblog#1]
### 为什么9001端口打开是这样
![image](https://cloud.githubusercontent.com/assets/22772600/23751442/5b40cc16-050c-11e7-8089-604adad4fd80.png)
### 而默认的8080端口打开是这样
![image](https://cloud.githubusercontent.com/assets/22772600/23751475/84f55e5a-050c-11e7-9e78-736d16e6757d.png)
---
### 两个端口有什么区别？

**Comment by linguowei** [comment]
@FatDong1 如果你只是改了默认的监听端口没动其它代码的话页面是没有区别的，至于第二个页面的数据没出来可能是因为网络的原因，我源码里面连接的数据库是国外的一个数据库提供商的，可能会比较慢，你再重新刷新页面就好了
