### ISSUE TITLE
移动端 转 PC端 导航栏出现的bug

### ISSUE THREAD

**Issue by Ghostdar** [linguowei/myblog#4]
切换到移动端模拟器打开导航栏之后，再切回PC发现2个导航栏。
![image](https://user-images.githubusercontent.com/17442718/29309124-fb16a7b0-81da-11e7-8360-8e854ac8887d.png)

**Comment by linguowei** [comment]
@Ghostdar 谢谢你的反馈，近段我会用`Angular`把该博客系统进行重构，这个`vue`版本的就不再维护了
